#!/bin/bash
# Quick Start Guide: Publishing to Ansible Galaxy

echo "========================================="
echo "Ansible Galaxy Publishing Guide"
echo "========================================="
echo ""

echo "STEP 1: Prepare Your Collection"
echo "---------------------------------"
echo "✓ Tests passing: Run 'pytest tests/unit/'"
echo "✓ Documentation complete: Check README.md"
echo "✓ Examples working: Test all playbooks"
echo "✓ License correct: Verify galaxy.yml"
echo ""

echo "STEP 2: Build the Collection"
echo "-----------------------------"
echo "Run:"
echo "  ansible-galaxy collection build"
echo ""
echo "This creates: cisco-iosxe_gnmi-1.0.0.tar.gz"
echo ""

echo "STEP 3: Test Installation Locally"
echo "----------------------------------"
echo "Run:"
echo "  ansible-galaxy collection install cisco-iosxe_gnmi-1.0.0.tar.gz --force"
echo ""
echo "Verify:"
echo "  ansible-galaxy collection list | grep iosxe_gnmi"
echo ""

echo "STEP 4: Create Ansible Galaxy Account"
echo "---------------------------------------"
echo "1. Go to: https://galaxy.ansible.com"
echo "2. Click 'Sign in with GitHub'"
echo "3. Authorize Ansible Galaxy"
echo "4. Go to 'My Content' -> 'Namespaces'"
echo "5. Create or claim namespace 'cisco'"
echo ""

echo "STEP 5: Get API Token"
echo "----------------------"
echo "1. Go to: https://galaxy.ansible.com/me/preferences"
echo "2. Click 'API Key' tab"
echo "3. Click 'Show' or create new token"
echo "4. Copy the token"
echo ""

echo "STEP 6: Publish to Galaxy"
echo "--------------------------"
echo "Option A - Via Web Interface:"
echo "  1. Go to: https://galaxy.ansible.com/my-content/namespaces"
echo "  2. Click on your namespace"
echo "  3. Click 'Upload collection'"
echo "  4. Select: cisco-iosxe_gnmi-1.0.0.tar.gz"
echo "  5. Click 'Upload'"
echo ""
echo "Option B - Via Command Line:"
echo "  ansible-galaxy collection publish cisco-iosxe_gnmi-1.0.0.tar.gz --api-key=<YOUR_API_KEY>"
echo ""

echo "STEP 7: Verify Publication"
echo "---------------------------"
echo "1. Visit: https://galaxy.ansible.com/cisco/iosxe_gnmi"
echo "2. Check version, documentation, download count"
echo "3. Test installation from Galaxy:"
echo "   ansible-galaxy collection install cisco.iosxe_gnmi"
echo ""

echo "STEP 8: Promote Your Collection"
echo "--------------------------------"
echo "✓ Tweet about it with #Ansible #Cisco #gNMI"
echo "✓ Post on Reddit r/ansible"
echo "✓ Share on LinkedIn"
echo "✓ Blog post with examples"
echo "✓ Present at Ansible meetups"
echo "✓ Add to Awesome Ansible lists"
echo ""

echo "STEP 9: Maintain Your Collection"
echo "---------------------------------"
echo "✓ Monitor GitHub issues"
echo "✓ Respond to user questions"
echo "✓ Release updates regularly"
echo "✓ Keep documentation current"
echo "✓ Test with new Ansible versions"
echo ""

echo "========================================="
echo "For cisco.ios Contribution"
echo "========================================="
echo ""
echo "STEP 1: Open Discussion"
echo "------------------------"
echo "1. Go to: https://github.com/ansible-collections/cisco.ios/issues"
echo "2. Create new issue: 'Proposal: Add gNMI Support'"
echo "3. Describe benefits and use cases"
echo "4. Link to your Galaxy collection"
echo "5. Offer to contribute"
echo ""

echo "STEP 2: Fork and Prepare"
echo "------------------------"
echo "  git clone https://github.com/ansible-collections/cisco.ios.git"
echo "  cd cisco.ios"
echo "  git checkout -b feature/add-gnmi-support"
echo ""

echo "STEP 3: Add Your Code"
echo "---------------------"
echo "  # Copy module"
echo "  cp /path/to/cisco_iosxe_gnmi.py plugins/modules/"
echo "  cp /path/to/gnmi_client.py plugins/module_utils/"
echo ""
echo "  # Add tests"
echo "  cp -r /path/to/tests/* tests/"
echo ""
echo "  # Update docs"
echo "  # Add to CHANGELOG.rst"
echo ""

echo "STEP 4: Test Integration"
echo "-------------------------"
echo "  # Run their test suite"
echo "  ansible-test units --docker"
echo "  ansible-test sanity --docker"
echo "  ansible-test integration --docker"
echo ""

echo "STEP 5: Submit PR"
echo "------------------"
echo "  git add ."
echo "  git commit -m 'Add gNMI support for IOS XE devices'"
echo "  git push origin feature/add-gnmi-support"
echo ""
echo "Then create PR on GitHub with:"
echo "  - Clear description"
echo "  - Link to issue"
echo "  - Test results"
echo "  - Examples of usage"
echo ""

echo "========================================="
echo "Useful Commands"
echo "========================================="
echo ""
echo "# Build collection"
echo "ansible-galaxy collection build"
echo ""
echo "# Install locally"
echo "ansible-galaxy collection install cisco-iosxe_gnmi-1.0.0.tar.gz"
echo ""
echo "# Publish to Galaxy"
echo "ansible-galaxy collection publish cisco-iosxe_gnmi-1.0.0.tar.gz --api-key=\$GALAXY_API_KEY"
echo ""
echo "# List installed collections"
echo "ansible-galaxy collection list"
echo ""
echo "# Verify module is available"
echo "ansible-doc cisco.iosxe_gnmi.cisco_iosxe_gnmi"
echo ""

echo "========================================="
echo "Resources"
echo "========================================="
echo ""
echo "Ansible Galaxy: https://galaxy.ansible.com"
echo "Collection Guide: https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html"
echo "cisco.ios Repo: https://github.com/ansible-collections/cisco.ios"
echo "DevNet Support: devnetsupport@cisco.com"
echo ""
echo "Good luck! 🚀"
