# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: factory_reset.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'factory_reset.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66\x61\x63tory_reset.proto\x12\x12gnoi.factory_reset\x1a\x0btypes.proto\"K\n\x0cStartRequest\x12\x12\n\nfactory_os\x18\x01 \x01(\x08\x12\x11\n\tzero_fill\x18\x02 \x01(\x08\x12\x14\n\x0cretain_certs\x18\x03 \x01(\x08\"\x0e\n\x0cResetSuccess\"j\n\nResetError\x12\x1e\n\x16\x66\x61\x63tory_os_unsupported\x18\x01 \x01(\x08\x12\x1d\n\x15zero_fill_unsupported\x18\x02 \x01(\x08\x12\r\n\x05other\x18\x03 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\"\x8d\x01\n\rStartResponse\x12\x39\n\rreset_success\x18\x01 \x01(\x0b\x32 .gnoi.factory_reset.ResetSuccessH\x00\x12\x35\n\x0breset_error\x18\x02 \x01(\x0b\x32\x1e.gnoi.factory_reset.ResetErrorH\x00\x42\n\n\x08response2\\\n\x0c\x46\x61\x63toryReset\x12L\n\x05Start\x12 .gnoi.factory_reset.StartRequest\x1a!.gnoi.factory_reset.StartResponseB2Z(github.com/openconfig/gnoi/factory_reset\xd2>\x05\x30.1.0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'factory_reset_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/openconfig/gnoi/factory_reset\322>\0050.1.0'
  _globals['_STARTREQUEST']._serialized_start=56
  _globals['_STARTREQUEST']._serialized_end=131
  _globals['_RESETSUCCESS']._serialized_start=133
  _globals['_RESETSUCCESS']._serialized_end=147
  _globals['_RESETERROR']._serialized_start=149
  _globals['_RESETERROR']._serialized_end=255
  _globals['_STARTRESPONSE']._serialized_start=258
  _globals['_STARTRESPONSE']._serialized_end=399
  _globals['_FACTORYRESET']._serialized_start=401
  _globals['_FACTORYRESET']._serialized_end=493
# @@protoc_insertion_point(module_scope)
